# Generated by Django 5.0.7 on 2024-07-28 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_customuser_apellido_materno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='apellido materno'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True, verbose_name='género'),
        ),
    ]
