# Generated by Django 5.0.7 on 2024-08-05 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
        ('usuarios', '0003_alter_customuser_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='posgrado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generales.posgrado', verbose_name='Posgrado'),
        ),
    ]
